name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  checks:
    name: Check project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare runner
        run: sudo apt install wabt

      - name: xtask ci
        run: cargo xtask ci
