name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  checks:
    name: Check project
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: xtask ci
        run: cargo xtask ci
